#!/bin/bash

app_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$app_path/package/check-ffmpeg.sh"
source "$app_path/package/read-settings.sh"
source "$app_path/package/check-common-args.sh"

if [ $# -lt 3 -o "$1" = "-help" -o "$1" = "-h" ]; then
  echo "NAME" >&2
  echo -e "\tvcut - Cut input" >&2
  echo "" >&2
  echo "SYNOPSIS" >&2
  echo -e "\tvcut INPUT(-) START_SEC END_SEC [OPTIONS]" >&2
  echo -e "\tIf using pipe input, INPUT should be \"-\""
  echo "" >&2
  echo "OPTIONS" >&2
  echo -e "\t-h, -help\t\tShow help" >&2
  echo -e "\t-v, -version\t\tShow version" >&2
  echo -e "\t-o, -output FILE\tOutput file" >&2
  echo -e "\t-copyright\t\tShow copyright" >&2
  exit 1
fi

IN="$1"
START="$2"
END="$3"
if [ "$4" = "-o" -o "$4" = "-output" ]; then
  OUT="${5:--}"
fi

DURATION=$((END - START))
ENCODING=$(readSetting encoding)

if [ "$IN" = "-" ]; then
  INPUT="pipe:0"
else
  INPUT="$IN"
fi
if [ "$OUT" = "-" ]; then
  OUTPUT="pipe:1"
else
  OUTPUT="$OUT"
fi

echo "[vcut] start video cut" >&2

ffmpeg \
  -i "$INPUT" \
  -ss "$START" -t "$DURATION" \
  -c:v $ENCODING -c:a aac \
  -f mp4 -movflags frag_keyframe+empty_moov \
  "$OUTPUT" -loglevel error -stats

echo "[vcut] finish video cut" >&2